Contribuciones
epiverse-trace/epitkit pull request #9
Opened 2024-10-11 22:43 UTC by Joskerus

* **Please check if the PR fulfills these requirements**

- [ ] I have read the CONTRIBUTING guidelines
- [ ] A new item has been added to `NEWS.md`
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Checks have been run locally and pass

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2024-10-11 22:44 UTC, Joskerus commented
Cambios a las unidades y glosario

2024-10-16 18:07 UTC, avallecam requested changes
Gracias por la actualizacion! Solo solicito que aceptes los cambios del formato de tablas en markdown, porque se construyen con espacios entre palabras. Una herramienta que funciona bien es https://www.tablesgenerator.com/markdown_tables

2024-10-16 18:07 UTC, avallecam commented on learners/reference.md
> ++--------------------------------+----------------+------------+------------+
with https://www.tablesgenerator.com/markdown_tables# we build a fix tables for markdown

```suggestion
|  | Enfermos | Sanos | Total |
|---|---|---|---|
| **Estudiantes primaria** | 30 | 120 | 150 |
| **Estudiantes secondaria** | 5 | 135 | 140 |
| Total | 35 | 265 | 290 |
```

2024-10-16 18:07 UTC, avallecam commented on learners/reference.md
> ++---------------------------+------------------+---------------+-----------+
```suggestion
|  | Enfermos (Casos) | Sanos (Controles) | Total |
|---|---|---|---|
| **Expuestos (Consumió Sandwish)** | 35 | 25 | 60 |
| **No expuestos (No consumió Sandwish)** | 15 | 25 | 40 |
| Total | 50 | 50 | 100 |
```

2024-10-17 12:27 UTC, avallecam commented
listo para el merge 🚀 

en una actualizacion aparte podemos convertir el glosario en Rmd para que pueda alojar el codigo de la imagen que compara R0 #11

2024-10-17 12:27 UTC, merged